name: CSV Action

on:
  push:
    branches:
      - main

jobs:
  csv-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read and print CSV
        run: |
          cat archivo.csv
